server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newdb?characterEncoding=utf8&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 50MB
      # 所有上传文件最大大小
      max-request-size: 50MB
#  servlet:
#    multipart:
#      max-file-size: 1024Mb
#      max-request-size: 1024Mb


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
files:
  upload:
    path: D:\DeskTop\program\GithubPro\files\

